### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by szage2** [szage2/BirthdayReminder#5]
Need to setup MySQL reachable by the main node.js app

**Comment by norbert-gaspar** [comment]
**Creating MariaDB image for Raspberry Pi:**
https://peppe8o.com/create-a-custom-mariadb-container-with-raspberry-pi-and-docker/

**Comment by norbert-gaspar** [comment]
**Installing PHPMyAdmin and connecting it to MariaDB:**
https://blog.thenets.org/how-to-install-mysql-and-phpmyadmin-with-docker/

**Comment by norbert-gaspar** [comment]
DB is up and running for the currently required demo purposes. As agreed with @szage2 production DB will be setup later.

**Comment by norbert-gaspar** [comment]
Recreated the database with PMA installation. The trick to redeployment was not adding a volume (something to be fixed on the long run, but fair workaround for initial testing purposes).
