### ISSUE TITLE
Add redundant free hosting solution

### ISSUE THREAD

**Issue by norbert-gaspar** [szage2/BirthdayReminder#6]
Originally used 000webhost is notoriously unreliable - Need another host as a backup plan

**Comment by norbert-gaspar** [comment]
The fallback option is super slow (using this option it takes about 5 minutes to see the result of a commit). But 000webhost is still down and this service provider at least works. Left this one as the default option in for now.

**Comment by szage2** [comment]
Link here the new path please @norbert-gaspar .

**Comment by norbert-gaspar** [comment]
http://homestackapi.unaux.com
